#!/usr/bin/env python3

from typing import TYPE_CHECKING
if TYPE_CHECKING:
  from ambuild2.context import Context
  builder: Context
  TestProgram: object

import os

projectName = 'testprogram_exec' 

for cxx in builder.targets:
  binary = cxx.Program(projectName)
  TestProgram.AddKHook(binary)
  binary.sources += [
    'main.cpp'
  ]
  builder.Add(binary)