#!/usr/bin/env python

from typing import TYPE_CHECKING
if TYPE_CHECKING:
  from ambuild2.context import Context
  builder: Context
  TestRunner: object

import os

projectName = 'testrunner' 

for cxx in builder.targets:
  binary = cxx.Program(projectName)
  TestRunner.AddKHook(binary)
  TestRunner.AddGTest(binary)
  binary.sources += [
    'main.cpp',
    'virtual.cpp'
  ]
  
  TestRunner.binaries += [ builder.Add(binary) ]